name = "mcp-worker"
main = "src/worker.js"
compatibility_date = "2025-11-01"

[[r2_buckets]]
binding = "R2"
bucket_name = "lamagent"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "ai-search-lamagent-ai-search"

[ai]
binding = "AI"